# Generated by Django 4.1.2 on 2022-11-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_alter_message_is_read_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_from',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_message', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения'),
        ),
    ]
