# Generated by Django 4.1.2 on 2022-11-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_message_sent_from_remove_message_sent_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
