# Generated by Django 4.1.2 on 2022-11-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_rename_chat_id_message_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('sent_time',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
