# Generated by Django 4.1.2 on 2022-12-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.CharField(default='', max_length=900000),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.CharField(default='', max_length=900000),
        ),
        migrations.AddField(
            model_name='message',
            name='location',
            field=models.CharField(default='', max_length=900000),
        ),
    ]
