# Generated by Django 4.1.2 on 2022-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_message_audio_message_file_message_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.CharField(default='', max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.CharField(default='', max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='location',
            field=models.CharField(default='', max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default='', max_length=900000, null=True),
        ),
    ]
