# Generated by Django 4.1.2 on 2022-12-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_message_audio_alter_message_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-sent_time',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
